/**
 * TranslateToUrdu Component
 * React component for Urdu translation functionality
 */

import React, { useState, useEffect } from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';

const TranslateToUrduComponent = ({
  children,
  enableTranslation = true,
  autoTranslate = false
}) => {
  const [translatedContent, setTranslatedContent] = useState(children);
  const [isTranslated, setIsTranslated] = useState(autoTranslate);
  const [loading, setLoading] = useState(false);

  // Urdu translation mappings for common terms
  const urduMappings = {
    'introduction': 'تعارف',
    'robotics': 'روبوٹکس',
    'artificial intelligence': 'مصنوعی ذہانت',
    'ai': 'مذ',
    'machine learning': 'مشین لرننگ',
    'deep learning': 'گہرائی سیکھنا',
    'neural network': 'نیورل نیٹ ورک',
    'algorithm': 'الگورتھم',
    'programming': 'پروگرامنگ',
    'code': 'کوڈ',
    'function': 'فنکشن',
    'variable': 'متغیر',
    'loop': 'لوپ',
    'condition': 'حالت',
    'robot': 'روبوٹ',
    'sensor': 'سینسر',
    'actuator': 'ایکچوایٹر',
    'motor': 'موٹر',
    'controller': 'کنٹرولر',
    'navigation': 'نیویگیشن',
    'perception': 'ادراک',
    'planning': 'منصوبہ بندی',
    'execution': 'عمل',
    'simulation': 'سیمولیشن',
    'gazebo': 'گزیبو',
    'ros': 'ROS',
    'ros 2': 'ROS 2',
    'humble': 'Humbe',
    'jetson': 'جیٹسن',
    'nx': 'این ایکس',
    'nvidia': 'این ویڈیا',
    'hardware': 'ہارڈ ویئر',
    'software': 'سافٹ ویئر',
    'development': 'تعمیر',
    'development environment': 'تعمیر کا ماحول',
    'environment': 'ماحول',
    'learning': 'سیکھنا',
    'module': 'ماڈیول',
    'chapter': 'باب',
    'section': 'حصہ',
    'topic': 'موضوع',
    'concept': 'تصور',
    'example': 'مثال',
    'exercise': 'ورکشاپ',
    'practice': 'مشق',
    'skill': 'مہارت',
    'beginner': 'ابتدائی',
    'intermediate': 'درمیانہ',
    'advanced': 'اعلیٰ',
    'difficulty': 'مشکل',
    'level': 'سطح',
    'progress': 'پیشرفت',
    'completion': 'مکمل ہونا',
    'completed': 'مکمل',
    'understanding': 'سمجھ',
    'comprehension': 'ادراک',
    'knowledge': 'علم',
    'expert': 'ماہر',
    'subagent': 'سب ایجنٹ',
    'assistant': 'مددگار',
    'help': 'مدد',
    'guide': 'راہ نما',
    'tutorial': 'سیکھنے کا طریقہ',
    'documentation': 'دستاویزات',
    'reference': 'حوالہ',
    'resource': 'وسائل',
    'tool': 'اوزار',
    'framework': 'چوکھٹ',
    'library': 'لائبریری',
    'package': 'پیکیج',
    'dependency': 'وابستگی',
    'installation': 'تنصیب',
    'setup': 'سیٹ اپ',
    'configuration': 'تشکیل',
    'validation': 'توثیق',
    'verification': 'توثیق',
    'test': 'ٹیسٹ',
    'testing': 'ٹیسٹنگ',
    'debug': 'ڈیبگ',
    'debugging': 'ڈیبگنگ',
    'error': 'غلطی',
    'bug': 'بگ',
    'fix': 'ٹھیک کریں',
    'solution': 'حل',
    'problem': 'مسئلہ',
    'challenge': 'چیلنج',
    'task': 'کام',
    'project': 'پروجیکٹ',
    'application': 'اطلاقیہ',
    'implementation': 'نافذ کرنا',
    'real-world': 'حقیقی دنیا',
    'practical': 'عملی',
    'theory': 'نظریہ',
    'practice': 'مشق',
    'hands-on': 'ہاتھوں سے',
    'interactive': 'مinteractive',
    'personalization': 'ذاتی نوعیت',
    'adaptive': 'مطابقت پذیر',
    'customization': 'اپنی مرضی کے مطابق',
    'preference': 'ترجیح',
    'user': 'صارف',
    'profile': 'پروفائل',
    'language': 'زبان',
    'english': 'انگریزی',
    'urdu': 'اردو',
    'begin': 'شروع کریں',
    'start': 'شروع',
    'continue': 'جاری رکھیں',
    'next': 'اگلا',
    'previous': 'پچھلا',
    'end': 'ختم',
    'finish': 'ختم کریں',
    'complete': 'مکمل',
    'done': 'ہو گیا',
    'success': 'کامیابی',
    'achieve': 'حاصل کریں',
    'goal': 'ہدف',
    'objective': 'مقصد',
    'target': 'ہدف',
    'aim': 'ہدف',
    'purpose': 'مقصد',
    'reason': 'وجہ',
    'why': 'کیوں',
    'how': 'کیسے',
    'what': 'کیا',
    'where': 'کہاں',
    'when': 'کب',
    'who': 'کون',
    'which': 'کون سا',
    'can': 'کر سکتا ہے',
    'will': 'کرے گا',
    'should': 'چاہیے',
    'must': 'ضرور',
    'may': 'شاید',
    'might': 'شاید',
    'could': 'کر سکتا تھا',
    'would': 'کرتا',
    'if': 'اگر',
    'then': 'پھر',
    'else': 'ورنہ',
    'for': 'کے لیے',
    'to': 'کو',
    'of': 'کا',
    'and': 'اور',
    'or': 'یا',
    'not': 'نہیں',
    'is': 'ہے',
    'are': 'ہیں',
    'was': 'تھا',
    'were': 'تھے',
    'be': 'ہونا',
    'been': 'ہوا',
    'being': 'ہوتے ہوئے',
    'have': 'رکھتا ہے',
    'has': 'رکھتا ہے',
    'had': 'رکھا',
    'do': 'کرنا',
    'does': 'کرتا ہے',
    'did': 'کیا',
    'say': 'کہنا',
    'says': 'کہتا ہے',
    'said': 'کہا',
    'get': 'حاصل کرنا',
    'got': 'حاصل کیا',
    'go': 'جانا',
    'goes': 'جاتا ہے',
    'went': 'گیا',
    'make': 'بنانا',
    'makes': 'بنا دیتا ہے',
    'made': 'بنایا',
    'take': 'لینا',
    'takes': 'لیتا ہے',
    'took': 'لیا',
    'see': 'دیکھنا',
    'sees': 'دیکھتا ہے',
    'saw': 'دیکھا',
    'come': 'آنا',
    'comes': 'آتا ہے',
    'came': 'آیا',
    'think': 'سوچنا',
    'thinks': 'سوچتا ہے',
    'thought': 'سوچا',
    'look': 'دیکھنا',
    'looks': 'دیکھتا ｈے',
    'looked': 'دیکھا',
    'want': 'چاہنا',
    'wants': 'چاہتا ہے',
    'wanted': 'چاہتا تھا',
    'give': 'دینا',
    'gives': 'دیتا ہے',
    'gave': 'دیا',
    'use': 'استعمال کرنا',
    'uses': 'استعمال کرتا ہے',
    'used': 'استعمال کیا',
    'find': 'ڈھونڈنا',
    'finds': 'ڈھونڈتا ہے',
    'found': 'ڈھونڈ لیا',
    'tell': 'بتانا',
    'tells': 'بتاتا ہے',
    'told': 'بتایا',
    'ask': 'پوچھنا',
    'asks': 'پوچھتا ہے',
    'asked': 'پوچھا',
    'work': 'کام',
    'works': 'کام کرتا ہے',
    'worked': 'کام کیا',
    'seem': 'لگتا ہے',
    'seems': 'لگتا ہے',
    'seemed': 'لگا',
    'feel': 'محسوس کرنا',
    'feels': 'محسوس کرتا ہے',
    'felt': 'محسوس کیا',
    'try': 'کوشش کرنا',
    'tries': 'کوشش کرتا ہے',
    'tried': 'کوشش کی',
    'leave': 'چھوڑنا',
    'leaves': 'چھوڑ دیتا ہے',
    'left': 'چھوڑ دیا',
    'call': 'کال کرنا',
    'calls': 'کال کرتا ہے',
    'called': 'کال کی',
    'need': 'ضرورت ہے',
    'needs': 'ضرورت ہے',
    'needed': 'ضرورت تھی',
    'become': 'بننا',
    'becomes': 'بنتا ہے',
    'became': 'بن گیا',
    'happen': 'ہونا',
    'happens': 'ہوتا ہے',
    'happened': 'ہوا',
    'show': 'دکھانا',
    'shows': 'دکھاتا ہے',
    'showed': 'دکھایا',
    'mean': 'مطلب',
    'means': 'مطلب ہے',
    'meant': 'مطلب تھا',
    'put': 'ڈالنا',
    'set': 'سیٹ کرنا',
    'sets': 'سیٹ کرتا ہے',
    'set': 'سیٹ',
    'help': 'مدد',
    'helps': 'مدد کرتا ہے',
    'helped': 'مدد کی',
    'play': 'کھیلنا',
    'plays': 'کھیلتا ہے',
    'played': 'کھیلا',
    'run': 'چلنا',
    'runs': 'چلتا ہے',
    'ran': 'چلا',
    'move': 'منتقل ہونا',
    'moves': 'منتقل ہوتا ہے',
    'moved': 'منتقل ہو گیا',
    'live': 'رہنا',
    'lives': 'رہتا ہے',
    'lived': 'رہا',
    'believe': 'یقین کرنا',
    'believes': 'یقین رکھتا ہے',
    'believed': 'یقین کیا',
    'hold': 'پکڑنا',
    'holds': 'پکڑتا ہے',
    'held': 'پکڑا',
    'bring': 'لانا',
    'brings': 'لاتا ہے',
    'brought': 'لایا',
    'must': 'ضرور',
    'should': 'چاہیے',
    'would': 'کرے گا',
    'could': 'کر سکتا ہے',
    'can': 'کر سکتا ہے',
    'will': 'کرے گا',
    'shall': 'کرے گا',
    'yes': 'ہاں',
    'no': 'نہیں',
    'not': 'نہیں',
    'ok': 'ٹھیک ہے',
    'okay': 'ٹھیک ہے',
    'good': 'اچھا',
    'great': 'عظیم',
    'excellent': 'شاندار',
    'amazing': 'اچھا',
    'wonderful': 'اچھا',
    'fantastic': 'شاندار',
    'perfect': 'کامل',
    'right': 'صحیح',
    'correct': 'صحیح',
    'wrong': 'غلط',
    'bad': 'برا',
    'terrible': 'بُرا',
    'awful': 'بُرا',
    'poor': 'غریب',
    'rich': 'امیر',
    'big': 'بڑا',
    'large': 'بڑا',
    'huge': 'بہت بڑا',
    'small': 'چھوٹا',
    'little': 'چھوٹا',
    'tiny': 'ننھا',
    'short': 'چھوٹا',
    'long': 'لمبا',
    'tall': 'لمبا',
    'high': 'چنا',
    'low': 'کم',
    'deep': 'گہرا',
    'shallow': 'چھرا',
    'wide': 'چوڑا',
    'narrow': 'تنگ',
    'thick': 'موٹا',
    'thin': 'پتلی',
    'heavy': 'بھاری',
    'light': 'ہلکا',
    'fast': 'تیز',
    'quick': 'تیز',
    'slow': 'سست',
    'late': 'دیر',
    'early': 'جلد',
    'new': 'نیا',
    'old': 'پرانا',
    'young': 'نوجوان',
    'ancient': 'قدیم',
    'modern': 'جدید',
    'future': 'مستقبل',
    'past': 'ماضی',
    'present': 'حال',
    'now': 'اب',
    'then': 'پھر',
    'today': 'آج',
    'tomorrow': 'کل',
    'yesterday': 'کل',
    'morning': 'صبح',
    'afternoon': 'دوپہر',
    'evening': 'شام',
    'night': 'رات',
    'day': 'دن',
    'week': 'ہفتہ',
    'month': 'مہینہ',
    'year': 'سال',
    'time': 'وقت',
    'moment': 'لمحہ',
    'hour': 'گھنٹہ',
    'minute': 'منٹ',
    'second': 'سیکنڈ',
    'first': 'پہلا',
    'second': 'دوسرا',
    'third': 'تیسرا',
    'last': 'آخری',
    'next': 'اگلا',
    'previous': 'پچھلا',
    'one': 'ایک',
    'two': 'دو',
    'three': 'تین',
    'four': 'چار',
    'five': 'پانچ',
    'six': 'چھ',
    'seven': 'سات',
    'eight': 'آٹھ',
    'nine': 'نو',
    'ten': 'دس',
    'eleven': 'گیارہ',
    'twelve': 'بارہ',
    'thirteen': 'تیرہ',
    'fourteen': 'چودہ',
    'fifteen': 'پندرہ',
    'sixteen': 'سولہ',
    'seventeen': 'سترہ',
    'eighteen': 'اٹھارہ',
    'nineteen': 'انیس',
    'twenty': 'بیس',
    'thirty': 'تیس',
    'forty': 'چالیس',
    'fifty': 'پچاس',
    'sixty': 'سٹھ',
    'seventy': 'ستر',
    'eighty': 'اسی',
    'ninety': 'نوے',
    'hundred': 'سو',
    'thousand': 'ہزار',
    'million': 'ملین',
    'billion': 'بلین',
    'more': 'مزید',
    'less': 'کم',
    'many': 'بہت',
    'much': 'بہت',
    'few': 'کم',
    'several': 'کئی',
    'all': 'سب',
    'every': 'ہر',
    'each': 'ہر ایک',
    'some': 'کچھ',
    'any': 'کوئی',
    'none': 'کوئی نہیں',
    'nothing': 'کچھ نہیں',
    'everything': 'سب کچھ',
    'something': 'کچھ',
    'anything': 'کوئی چیز',
    'here': 'یہاں',
    'there': 'وہاں',
    'where': 'کہاں',
    'this': 'یہ',
    'that': 'وہ',
    'these': 'یہ',
    'those': 'وہ',
    'who': 'کون',
    'what': 'کیا',
    'which': 'کون سا',
    'whose': 'جس کا',
    'whom': 'جسے',
    'when': 'کب',
    'where': 'کہاں',
    'why': 'کیوں',
    'how': 'کیسے',
    'i': 'میں',
    'you': 'آپ',
    'he': 'وہ',
    'she': 'وہ',
    'it': 'یہ',
    'we': 'ہم',
    'they': 'وہ',
    'me': 'مجھے',
    'him': 'اسے',
    'her': 'اسے',
    'us': 'ہمیں',
    'them': 'انہیں',
    'my': 'میرا',
    'your': 'آپ کا',
    'his': 'اس کا',
    'her': 'اس کا',
    'its': 'اس کا',
    'our': 'ہمارا',
    'their': 'ان کا',
    'mine': 'میرا',
    'yours': 'آپ کا',
    'hers': 'اس کا',
    'ours': 'ہمارا',
    'theirs': 'ان کا',
    'myself': 'خود',
    'yourself': 'آپ خود',
    'himself': 'خود',
    'herself': 'خود',
    'itself': 'خود',
    'ourselves': 'خود',
    'yourselves': 'آپ خود',
    'themselves': 'خود'
  };

  // Translate content using mappings
  const translateContent = (content) => {
    if (!content || typeof content !== 'string') {
      return content;
    }

    let translated = content;

    // Sort keys by length in descending order to avoid partial replacements
    const sortedKeys = Object.keys(urduMappings).sort((a, b) => b.length - a.length);

    for (const key of sortedKeys) {
      // Use word boundaries to avoid partial matches within words
      const regex = new RegExp(`\\b${key}\\b`, 'gi');
      translated = translated.replace(regex, (match) => {
        const lowerMatch = match.toLowerCase();
        const translation = urduMappings[lowerMatch];
        if (translation) {
          // Preserve original capitalization
          if (match === match.toUpperCase()) {
            return translation.toUpperCase();
          } else if (match === match.charAt(0).toUpperCase() + match.slice(1).toLowerCase()) {
            return translation.charAt(0).toUpperCase() + translation.slice(1).toLowerCase();
          }
          return translation;
        }
        return match; // Return original if no translation found
      });
    }

    return translated;
  };

  useEffect(() => {
    if (enableTranslation && isTranslated) {
      setLoading(true);
      // Simulate translation API call
      setTimeout(() => {
        setTranslatedContent(translateContent(children));
        setLoading(false);
      }, 100); // Small delay to simulate API call
    } else {
      setTranslatedContent(children);
    }
  }, [children, isTranslated, enableTranslation]);

  const toggleTranslation = () => {
    if (enableTranslation) {
      setIsTranslated(!isTranslated);
    }
  };

  return (
    <div className="translate-to-urdu">
      <div className="translation-controls">
        <button
          onClick={toggleTranslation}
          disabled={!enableTranslation}
          className={`translate-toggle ${isTranslated ? 'active' : ''}`}
        >
          {loading ? 'ترجمہ ہو رہا ہے...' : isTranslated ? 'انگریزی میں دیکھیں' : 'اردو میں ترجمہ کریں'}
        </button>
      </div>
      <div className="translated-content">
        {loading ? (
          <div className="loading">...لوڈ ہو رہا ہے</div>
        ) : (
          translatedContent
        )}
      </div>
    </div>
  );
};

// Wrapper component for browser-only rendering
const TranslateToUrdu = (props) => {
  return (
    <BrowserOnly>
      {() => <TranslateToUrduComponent {...props} />}
    </BrowserOnly>
  );
};

export default TranslateToUrdu;