import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Quarter Overview',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Module 1: ROS 2 Fundamentals',
          items: [{ type: 'autogenerated', dirName: 'quarter-overview/module-1-ros' }],
        },
        {
          type: 'category',
          label: 'Module 2: Gazebo & Unity Simulation',
          items: [{ type: 'autogenerated', dirName: 'quarter-overview/module-2-simulation' }],
        },
        {
          type: 'category',
          label: 'Module 3: NVIDIA Isaac Platform',
          items: [{ type: 'autogenerated', dirName: 'quarter-overview/module-3-perception' }],
        },
        {
          type: 'category',
          label: 'Module 4: VLA Implementation',
          items: [{ type: 'autogenerated', dirName: 'quarter-overview/module-4-ai-planning' }],
        },
      ],
    },
    {
      type: 'doc',
      id: 'why-physical-ai/index'
    },
    {
      type: 'doc',
      id: 'learning-outcomes/index'
    },
    {
      type: 'category',
      label: 'Weekly Breakdown',
      collapsed: false,
      items: [
        { type: 'autogenerated', dirName: 'weekly-breakdown' }
      ],
    },
    {
      type: 'doc',
      id: 'assessments/index'
    },
    {
      type: 'doc',
      id: 'hardware-reqs/index'
    },
    {
      type: 'category',
      label: 'Appendix',
      items: [{ type: 'autogenerated', dirName: 'appendix' }],
    },
    {
      type: 'category',
      label: 'Capstone',
      items: [{ type: 'autogenerated', dirName: 'capstone' }],
    },
    {
      type: 'category',
      label: 'Setup Guides',
      items: [{ type: 'autogenerated', dirName: 'setup-guides' }],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [{ type: 'autogenerated', dirName: 'api-reference' }],
    },
  ],
};

export default sidebars;
