# Controller configuration for JetBot simulation
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Joint state broadcaster
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Velocity controller for differential drive
    velocity_controller:
      type: diff_drive_controller/DiffDriveController

velocity_controller:
  ros__parameters:
    # Publish rate for the controller
    publish_rate: 50.0

    # Frame configuration
    base_frame_id: base_link
    odom_frame_id: odom
    publish_limited_tf: true

    # Wheels
    left_wheel_names: ["left_wheel"]
    right_wheel_names: ["right_wheel"]

    wheel_separation: 0.16
    wheel_radius: 0.033

    # Velocity commands
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 2.0
    linear.x.min_acceleration: -2.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

    # Odometry
    enable_odom_tf: true
    odom_only_publish: false
    position_feedback: true
    velocity_feedback: true
    open_loop: false

    # Topic names
    cmd_vel_topic: cmd_vel
    cmd_vel_timeout: 0.5
    odom_topic: odom
    publish_rate: 50.0